//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int Id { get; set; }
        public int Partner1 { get; set; }
        public int Name { get; set; }
        public int Director { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public int Adress { get; set; }
        public string INN { get; set; }
        public string Rate { get; set; }
    
        public virtual Adress Adress1 { get; set; }
        public virtual DirectorName DirectorName { get; set; }
        public virtual OrganizeName OrganizeName { get; set; }
        public virtual PartnetName PartnetName { get; set; }
    }
}
