//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProducts
    {
        public int Id { get; set; }
        public int Production { get; set; }
        public string ProductionDisrption { get; set; }
        public int PartnerName { get; set; }
        public int CountProduct { get; set; }
        public System.DateTime DateSell { get; set; }
    
        public virtual OrganizeName OrganizeName { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
    }
}
