//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public int TypeProduct { get; set; }
        public string ProductsDiscription { get; set; }
        public string Article { get; set; }
        public double MinPrice { get; set; }
    
        public virtual TypeProduct TypeProduct1 { get; set; }
    }
}
